version: '3.7'

services:

  web:
    container_name: aspnetcoreapp
    image: aspnetcoreapp
    build:
      context: .
      dockerfile: aspnetcore.dockerfile
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aspnetcoreapp
    ports:
        - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - aspnetcoreapp-network

volumes:
  db_data:
    driver: local

networks:
  aspnetcoreapp-network:
    driver: bridge